
{% set name = "stare" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SpatioTemporal/STARE/archive/{{ version }}.tar.gz
  sha256: 0ab1bb67ed322033fd4a43642a096058f6cacec231173d79553c8deb7391c4f8
build:
  number: 1
  skip: true  # [win]
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f $PREFIX/lib/libSTARE.so  # [not win]

about:
  home: https://github.com/SpatioTemporal/STARE
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'SpatioTemporal Adaptive Resolution Encoding for geodata space-time location'
  description: |
    STARE is a space-time location encoding for harmonizing diverse
    geodata without requiring interpolation to a common grid. This package
    is the C++ API library package used by pystare and STAREPandas, available
    via PyPi or from SpatioTemporal <https://github.com/SpatioTemporal>.
  dev_url: https://github.com/SpatioTemporal/STARE

extra:
  recipe-maintainers:
    - michaelleerilee
